//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trial
    {
        public int Size { get; set; }
        public string StartUtil { get; set; }
        public string Change { get; set; }
        public string Algorithm { get; set; }
        public double Entropy { get; set; }
        public double Power { get; set; }
        public double StdDev { get; set; }
        public double Hosts { get; set; }
        public double Migrations { get; set; }
        public double SlaViolations { get; set; }
        public double TotalMessages { get; set; }
        public string PredictionAlg { get; set; }
    }
}
